/*
 * MeMaS DP APIs
 *
 * This is the Data Plane APIs for MeMaS (Memory Management Service).
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: max.yu@memas.ai
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RecollectRequest {
    #[serde(rename = "clue", skip_serializing_if = "Option::is_none")]
    pub clue: Option<String>,
    /// \"Full name of a corpus, specifying which namespace the corpus is under.  The name takes on the format of \\\"<namespace_pathname>:<corpus_name>\\\"\"
    #[serde(rename = "corpus_pathname", skip_serializing_if = "Option::is_none")]
    pub corpus_pathname: Option<String>,
}

impl RecollectRequest {
    pub fn new() -> RecollectRequest {
        RecollectRequest {
            clue: None,
            corpus_pathname: None,
        }
    }
}


